
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: lakehouse-nessie
type: Opaque
data:
  postgres-password: <base64-encoded-secret-value>
  postgres-username: <base64-encoded-secret-value>

